"""
PDF Report Generator for Candidate Evaluations
Creates professional, industry-ready evaluation reports
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.platypus import PageBreak
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from io import BytesIO
from datetime import datetime


def create_evaluation_pdf(evaluation_data: dict, company_name: str = None) -> BytesIO:
    """
    Create a professional PDF evaluation report.
    
    Args:
        evaluation_data: Dictionary containing all evaluation information
        company_name: Name of the recruiting company
        
    Returns:
        BytesIO object containing the PDF
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.5*inch,
        leftMargin=0.5*inch,
        topMargin=0.5*inch,
        bottomMargin=0.5*inch
    )
    
    # Container for the 'Flowable' objects
    elements = []
    
    # Define styles
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#1e40af'),
        spaceAfter=12,
        alignment=TA_CENTER,
        fontName='Helvetica-Bold'
    )
    
    subtitle_style = ParagraphStyle(
        'CustomSubtitle',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#6b7280'),
        spaceAfter=20,
        alignment=TA_CENTER
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=14,
        textColor=colors.HexColor('#1e40af'),
        spaceAfter=8,
        spaceBefore=12,
        fontName='Helvetica-Bold'
    )
    
    body_style = ParagraphStyle(
        'CustomBody',
        parent=styles['Normal'],
        fontSize=10,
        textColor=colors.HexColor('#374151'),
        spaceAfter=6
    )
    
    # Header
    elements.append(Paragraph("CANDIDATE EVALUATION REPORT", title_style))
    elements.append(Paragraph(f"Generated by RecruBotX | {company_name or 'Your Company'}", subtitle_style))
    elements.append(Spacer(1, 0.1*inch))
    
    # Candidate Information Box
    candidate_info = [
        ['Candidate Name:', evaluation_data.get('candidateName', 'N/A')],
        ['Position:', evaluation_data.get('position', 'N/A')],
        ['Evaluation Date:', evaluation_data.get('date', datetime.now().strftime('%d-%m-%Y'))],
        ['Overall Score:', f"{evaluation_data.get('score', 'N/A')} - Rank #{evaluation_data.get('rank', 'N/A')}"],
        ['Interview Status:', evaluation_data.get('interviewStatus', 'N/A')]
    ]
    
    candidate_table = Table(candidate_info, colWidths=[2*inch, 4.5*inch])
    candidate_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#dbeafe')),
        ('BACKGROUND', (1, 0), (1, -1), colors.white),
        ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#1e40af')),
        ('ALIGN', (0, 0), (0, -1), 'RIGHT'),
        ('ALIGN', (1, 0), (1, -1), 'LEFT'),
        ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME', (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#93c5fd')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    elements.append(candidate_table)
    elements.append(Spacer(1, 0.15*inch))
    
    # Score Breakdown
    elements.append(Paragraph("Score Breakdown", heading_style))
    
    score_breakdown = [
        ['Component', 'Score', 'Weight', 'Contribution'],
        [
            'CV Screening',
            evaluation_data.get('cvScore', 'N/A'),
            '40%',
            f"{float(evaluation_data.get('cvScore', '0/100').split('/')[0]) * 0.4:.1f}"
        ],
        [
            'Interview Performance',
            evaluation_data.get('interviewScore', 'N/A'),
            '40%',
            f"{float(evaluation_data.get('interviewScore', '0/100').split('/')[0]) * 0.4:.1f}"
        ],
        [
            'Facial Recognition',
            evaluation_data.get('facialRecognitionScore', 'N/A'),
            '20%',
            f"{float(evaluation_data.get('facialRecognitionScore', '0/100').split('/')[0]) * 0.2:.1f}"
        ],
        [
            Paragraph("<b>Final Score</b>", body_style),
            Paragraph(f"<b>{evaluation_data.get('score', 'N/A')}</b>", body_style),
            Paragraph("<b>100%</b>", body_style),
            Paragraph(f"<b>{evaluation_data.get('score', '0/100').split('/')[0]}</b>", body_style)
        ]
    ]
    
    score_table = Table(score_breakdown, colWidths=[2.5*inch, 1.2*inch, 1.2*inch, 1.6*inch])
    score_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('TOPPADDING', (0, 0), (-1, 0), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#93c5fd')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -2), [colors.white, colors.HexColor('#f0f9ff')]),
        ('BACKGROUND', (0, -1), (-1, -1), colors.HexColor('#dbeafe')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 1), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
    ]))
    elements.append(score_table)
    elements.append(Spacer(1, 0.15*inch))
    
    # Skills Assessment
    elements.append(Paragraph("Skills Assessment", heading_style))
    
    skills_data = [['Skill', 'Score', 'Rating']]
    for skill in evaluation_data.get('skills', []):
        percentage = skill.get('percentage', 0)
        rating = '●●●●●' if percentage >= 80 else '●●●●○' if percentage >= 60 else '●●●○○' if percentage >= 40 else '●●○○○'
        skills_data.append([
            skill.get('name', 'N/A'),
            f"{percentage}%",
            rating
        ])
    
    skills_table = Table(skills_data, colWidths=[3*inch, 1.5*inch, 2*inch])
    skills_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('ALIGN', (1, 0), (1, -1), 'CENTER'),
        ('ALIGN', (2, 0), (2, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 11),
        ('FONTSIZE', (0, 1), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('TOPPADDING', (0, 0), (-1, 0), 10),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#93c5fd')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f0f9ff')]),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 1), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
    ]))
    elements.append(skills_table)
    elements.append(Spacer(1, 0.15*inch))
    
    # Two-column layout for Strengths and Weaknesses
    elements.append(Paragraph("Key Findings", heading_style))
    
    findings_data = [
        [
            Paragraph("<b>Strengths</b>", ParagraphStyle('StrengthTitle', parent=body_style, textColor=colors.HexColor('#059669'), fontName='Helvetica-Bold')),
            Paragraph("<b>Areas for Improvement</b>", ParagraphStyle('WeaknessTitle', parent=body_style, textColor=colors.HexColor('#dc2626'), fontName='Helvetica-Bold'))
        ]
    ]
    
    # Get strengths and weaknesses
    strengths = evaluation_data.get('strengths', ['Strong technical background', 'Good communication skills'])
    weaknesses = evaluation_data.get('weaknesses', ['Could improve problem-solving', 'Limited experience'])
    
    # Make them equal length
    max_len = max(len(strengths), len(weaknesses))
    strengths += [''] * (max_len - len(strengths))
    weaknesses += [''] * (max_len - len(weaknesses))
    
    for strength, weakness in zip(strengths, weaknesses):
        findings_data.append([
            Paragraph(f"• {strength}" if strength else "", body_style),
            Paragraph(f"• {weakness}" if weakness else "", body_style)
        ])
    
    findings_table = Table(findings_data, colWidths=[3.25*inch, 3.25*inch])
    findings_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#dbeafe')),
        ('GRID', (0, 0), (-1, -1), 1, colors.HexColor('#93c5fd')),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
    ]))
    elements.append(findings_table)
    elements.append(Spacer(1, 0.15*inch))
    
    # Recommendations
    if evaluation_data.get('recommendations'):
        elements.append(Paragraph("Recommendations", heading_style))
        elements.append(Paragraph(evaluation_data.get('recommendations', ''), body_style))
        elements.append(Spacer(1, 0.1*inch))
    
    # Footer
    footer_style = ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        fontSize=8,
        textColor=colors.HexColor('#9ca3af'),
        alignment=TA_CENTER
    )
    
    elements.append(Spacer(1, 0.2*inch))
    elements.append(Paragraph(
        f"This report was generated by RecruBotX on {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        footer_style
    ))
    elements.append(Paragraph(
        f"© {datetime.now().year} RecruBotX. All rights reserved. | Confidential Document",
        footer_style
    ))
    
    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer
